###

# curl https://api.openai.com/v1/chat/completions -u :$OPENAI_API_KEY -H 'Content-Type: application/json' -d '{
#  "model": "gpt-3.5-turbo-0613",
#  "messages": [
#    {"role": "user", "content": "What is the weather like in Boston?"},
#    {"role": "assistant", "content": null, "function_call": {"name": "get_current_weather", "arguments": "{ \"location\": \"Boston, MA\"}"}},
#    {"role": "function", "name": "get_current_weather", "content": "{\"temperature\": "22", \"unit\": \"celsius\", \"description\": \"Sunny\"}"}
#  ],
#  "functions": [
#    {
#      "name": "get_current_weather",
#      "description": "Get the current weather in a given location",
#      "parameters": {
#        "type": "object",
#        "properties": {
#          "location": {
#            "type": "string",
#            "description": "The city and state, e.g. San Francisco, CA"
#          },
#          "unit": {
#            "type": "string",
#            "enum": ["celsius", "fahrenheit"]
#          }
#        },
#        "required": ["location"]
#      }
#    }
#  ]
#}'
POST https://api.chatai.beauty/v1/chat/completions
Authorization: Bearer sk-chatAILogcgComkAqOklmUOqUrvjfvwuCWxzVr2deGmniJDHo
Content-Type: application/json

{
  "model": "gpt-3.5-turbo-0613",
  "messages": [
    {
      "role": "user",
      "content": "What is the weather like in Boston?"
    },
    {
      "role": "assistant",
      "content": "",
      "function_call": {
        "name": "get_current_weather",
        "arguments": "{ \"location\": \"Boston, MA\"}"
      }
    },
    {
      "role": "function",
      "name": "get_current_weather",
      "content": "{\"temperature\": \"22\", \"unit\": \"celsius\", \"description\": \"Sunny\"}"
    }
  ],
  "functions": [
    {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          },
          "unit": {
            "type": "string",
            "enum": [
              "celsius",
              "fahrenheit"
            ]
          }
        },
        "required": [
          "location"
        ]
      }
    }
  ]
}

<> 2023-12-30T190232.400.json
<> 2023-12-30T185851.400.json
<> 2023-12-30T185837.400.json
<> 2023-12-30T185514.403.json
<> 2023-12-30T185450.403.json
<> 2023-12-30T185419.404.html
<> 2023-12-30T185341.401.json

###

POST https://api.chatai.beauty/v1/chat/completions
Authorization: Bearer sk-chatAILogcgComkAqOklmUOqUrvjfvwuCWxzVr2deGmniJDHo
Content-Type: application/json

{
  "model": "gpt-3.5-turbo-0613",
  "messages": [
    {
      "role": "user",
      "content": "What is the weather like in Boston?"
    },
    {
      "role": "assistant",
      "content": "",
      "function_call": "{\"name\": \"get_current_weather\", \"arguments\": \"{ \"location\":\"Boston, MA\"}\"}"
    },
    {
      "role": "function",
      "name": "get_current_weather",
      "content": "{\"temperature\": \"22\", \"unit\": \"celsius\", \"description\": \"Sunny\"}"
    }
  ],
  "functions": [
    {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          },
          "unit": {
            "type": "string",
            "enum": [
              "celsius",
              "fahrenheit"
            ]
          }
        },
        "required": [
          "location"
        ]
      }
    }
  ]
}

